add exported wrapper for hashToField
armfazh/h2c-go-ref pull request #5
Opened 2020-08-06 23:15 UTC by tatianab

2020-08-07 20:59 UTC, armfazh requested changes
The general comment is that the field of the scalars is a different object from the field where the curve is defined.
You can find the prime modulus `h` in each curve definition.

2020-08-07 20:59 UTC, armfazh commented on hash.go
> +func (s *encodeToCurve) GetHashToScalar() HashToScalar {
The receiver of this method must be `encoding` as is shared between `encodeToCurve` and `hashToCurve` .

2020-08-07 20:59 UTC, armfazh commented on hash.go
> +	return s.FieldEncoding
However, the object returned must not be the field of the curve, but the field of the scalars.
You need to define the fields using the order of the curve as the prime modulus.

2020-08-07 20:59 UTC, armfazh commented on hash.go
> +type encoding struct {
You can augment this structure with a member that is the field of scalars.

2020-08-18 22:30 UTC, armfazh commented on suites.go
> +			ScalarField: field.NewFp("", E.Field().P()),
This is not the modulus of the scalar field: `E.Field().P()`, it should be the order of the curve.

2020-08-21 22:06 UTC, armfazh commented on go.sum
> +github.com/armfazh/tozan-ecc v0.1.2 h1:mhwrQnxiKqlDUdU5v6o6IBXF+CUPhuLAEIAH1gdIAf0=
run go  mod tidy

2020-08-21 22:08 UTC, tatianab commented on go.sum
> +github.com/armfazh/tozan-ecc v0.1.2 h1:mhwrQnxiKqlDUdU5v6o6IBXF+CUPhuLAEIAH1gdIAf0=
done

2020-08-25 00:53 UTC, armfazh approved these changes

2020-08-25 00:53 UTC, merged